project_name: kubehcl
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0

    main: ./main.go

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm

homebrew_casks:  
  - name: kubehcl  
    binary: kubehcl
    repository:
      owner: yanir75
      name: homebrew-apps
    hooks:
      post:
        # replace foo with the actual binary name
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubehcl"]
          end


nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    maintainer: 'yanir75'
    # homepage: ''
    description: >-
      kubehcl provides the option to deploy to kubernetes using hcl
    license: "MPL-2.0,Apache-2.0"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    rpm:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"
    deb:
      signature:
        key_file: "{{ if index .Env \"GPG_KEY_FILE\"  }}{{.Env.GPG_KEY_FILE}}{{ end }}"