project_name: kubehcl
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0

    main: ./main.go

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm

homebrew_casks:  
  - name: kubehcl  
    binary: kubehcl
    repository:
      owner: yanir75
      name: homebrew-apps
    hooks:
      post:
        # replace foo with the actual binary name
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubehcl"]
          end