name: Release

on:
  push:
    tags:
      - 'v*' # Trigger release on version tag push (e.g., v1.0.0)
      
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.24.1' ]
        os: [macos-latest]
    
    runs-on: ${{ matrix.os }}

    outputs:
      link: ${{ fromJSON(steps.upload.outputs.assets)[0].browser_download_url }}
      sha: ${{ steps.upload.outputs.sha }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
      
      - name: tar
        run:  tar -czf kubehcl.tar.gz kubehcl > /dev/null

      - name: sha
        id: sha
        run: echo "sha=$(shasum -a 256 kubehcl.tar.gz | awk '{print $1}' | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Upload release assets
        id: upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubehcl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  updateBrew:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="yanir75" 
          repo_name="homebrew-apps"  
          event_type="update-brew" 
          asset="${{ needs.build.outputs.link }}"
          version="${{ github.ref_name }}"
          sha="${{ needs.build.outputs.sha }}"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"asset\": \"$asset\", \"version\": \"$version\", \"sha\": \"$sha\"}}"
