name: Release

on:
  push:
    tags:
      - 'v*' # Trigger release on version tag push (e.g., v1.0.0)


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Create the .zip archive
      - name: Create .zip archive
        run: |
          zip -r repo.zip . > /dev/null

      # Create the .tar.gz archive
      - name: Create .tar.gz archive
        run: |
          tar -czf repo.tar.gz . > /dev/null

      # Upload release assets to GitHub Releases
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            repo.zip
            repo.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
