name: Release

on:
  push:
    tags:
      - 'v*' # Trigger release on version tag push (e.g., v1.0.0)
      
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.24.1' ]
        os: [macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build .
      
      - name: tar
        run:  tar -czf kubehcl.tar.gz kubehcl > /dev/null

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubehcl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}